project:
  type: manuscript
  output-dir: drafts

manuscript:
  article: paper.qmd
  # notebooks:
  #   - notebook1.ipynb
  #   - notebook2.ipynb

format:
  html:
    toc: true
    code-fold: true
    embed-resources: true
    self-contained-math: true
    output-file: paper.html
    comments:
      hypothesis: true
  docx: default
  jats: default
  # typst: default
  elsevier-pdf:
    output-file: 'manuscript.pdf'
    hyperrefoptions: 
      - "citecolor=black"
    echo: false
    journal:
      name: JASA-EL
      formatting: preprint
      model: 3p
      cite-style: authoryear

  # (other formats)
  # pdf: default

execute:
  freeze: true

